### ISSUE TITLE
Isolated tracks in 2016 nanoaod campaign

### ISSUE THREAD

**Issue by shane-breeze** [cms-nanoAOD/cmssw#122]
I hope this is the correct place to post this, but why aren't isolated tracks included in the nanoAOD 80X production?

It seems to be included in the 94X version it is just removed for the 80X sequence: https://github.com/cms-nanoAOD/cmssw/blob/master/PhysicsTools/NanoAOD/python/nano_cff.py#L104

Is there some bug/issue with the isoTrackSequence for 80X?

**Comment by gpetruc** [comment]
Il 16 Mar 2018 15:37, "shane-breeze" <notifications@github.com> ha scritto:

I hope this is the correct place to post this, but why aren't isolated
tracks included in the nanoAOD 80X production?

It seems to be included in the 94X version it is just removed for the 80X
sequence: https://github.com/cms-nanoAOD/cmssw/blob/master/
PhysicsTools/NanoAOD/python/nano_cff.py#L104

Is there some bug/issue with the isoTrackSequence for 80X?

they're not in nano because they're available in the 80X miniAOD to begin
with.
they'll be added when we do the re-miniAOD.

Giovanni

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/cms-nanoAOD/cmssw/issues/122>, or mute the thread

**Comment by arizzi** [comment]
https://twiki.cern.ch/twiki/bin/view/CMSPublic/WorkBookNanoAOD#Where_to_get_the_ntuples
