### ISSUE TITLE
which PDF set to use?

### ISSUE THREAD

**Issue by perrozzi** [cms-nanoAOD/cmssw#14]
are 103 replicas ok?
91200 | PDF4LHC15_nnlo_100_pdfas | 103
(@kdlong fyi)

**Comment by gpetruc** [comment]
switching to this thread, to nake @perrozzi happy (or to avoid BEING YELLED AT). adding @bendavid.
* 100 replicas is a lot in terms of disk space and burden to analyzers, for the purpose of propagating them through 10B events. 
* a proposal that doesn't cover the higgs group doesn't make a lot of sense to me since besides precision measurements (which won't be covered by any reduced set of weights) it's afaik the only group where there is interest and usecase to try to propagate pdf uncertainties consistently across all samples.
i understand that everyone likes their favourite set, but i think our goal matches what the pdf4lhc meta sets was designed to cover, and not a partisan choice.

**Comment by bendavid** [comment]
Using PDF4LHC as the default uncertainties also implies asking everyone by default to reweight the central value from nnpdf3.1 to pdf4lhc (which could be fine for most use cases, but is an additional complication)

Yes, agreed with the previous comment that a subset can make sense for MC replicas, but it was planned to switch to the hessians for the default in CMS since this is more flexible in terms of integration with statistical treatment (ie profiling of nuisance parameters).

**Comment by gpetruc** [comment]
On Tue, Sep 26, 2017 at 10:36 AM, Josh Bendavid <notifications@github.com>
wrote:

> Using PDF4LHC as the default uncertainties also implies asking everyone by
> default to reweight the central value from nnpdf3.1 to pdf4lhc (which could
> be fine for most use cases, but is an additional complication)
>
generating with pdf4lhc would have been the sensible thing to do, but
anyway reweighting the central is something trivial to do and that we could
also do centrally in nanoAOD.

Yes, agreed with the previous comment that a subset can make sense for MC
> replicas, but it was planned to switch to the hessians for the default in
> CMS since this is more flexible in terms of integration with statistical
> treatment (ie profiling of nuisance parameters).
>
I know, that's why I'm advocating for pdf4lhc15_nnlo_30 for 2017 MC (or the
nlo one, I don't know if there's been e.g. some negotiation with atlas for
future combinations)

however, we need something for 2016 MC (some will be re-generated with the
new tunes, but not all of it).

it would be great to be able to build a good approximation of the
pdf4lhc15_nnlo_30 central value and eigenvectors as weighted combinations
of the NNPDF 3.0 replicas that we have in the current samples (I believe we
discussed it with you some time ago), but I don't think we have the
expertise to do.

according to @peruzzim the 1000 nnpdf 3.0 replicas are not really random,
they're a choice selection ouf of 1000 random ones, so it could be that
they're "ordered" according to some criteria (that we don't know) and so
taking the first 50 may be a biased sub-sample, so we may have to think
more about it (e.g. pick out 50 at random out of the 100, or something
smarter?)

**Comment by gpetruc** [comment]
adding @dsperka @nucleosynthesis @giacomoortona to get info about what's needed for higgs combinations

**Comment by bendavid** [comment]
As far as I know the ordering the of the MC replicas is random for all sets which use MC replicas.  We can ask the authors.

As a reminder, we do also have the means to convert the 100 MC replica weights in existing 2016 samples to hessian weights with an arbitrary number of eigenvectors (with of course the accuracy of the uncertainty estimate degrading if the number gets too small).  There is an example in the release with 60 weights if I remember correctly.

**Comment by gpetruc** [comment]
On Tue, Sep 26, 2017 at 11:31 AM, Josh Bendavid <notifications@github.com>
wrote:

> As far as I know the ordering the of the MC replicas is random for all
> sets which use MC replicas. We can ask the authors.
>
> As a reminder, we do also have the means to convert the 100 MC replica
> weights in existing 2016 samples to hessian weights with an arbitrary
> number of eigenvectors (with of course the accuracy of the uncertainty
> estimate degrading if the number gets too small). There is an example in
> the release with 60 weights if I remember correctly.
>
Can you dig out a pointer?
We could use that with 60 for 2016 data, it's probably more practical than
50 replicas.
From the pdf4lhc15 note, mc2Hessian doesn't work terribly well with small
number, so maybe we can't push it down to 30 (their 30-component hessian
uses meta-pdf), and it still doesn't address 2016-2017 correlations, but
it's still an improvement.

**Comment by bendavid** [comment]
https://github.com/cms-sw/cmssw/blob/master/PhysicsTools/HepMCCandAlgos/plugins/PDFWeightsTest.cc

(the corresponding csv files with the conversion matrix are also in the cmssw release)

**Comment by jrueb** [comment]
Why is it that NanoAOD is using `PDF4LHC15_nnlo_30_pdfas` over `NNPDF31_nnlo_hessian_pdfas`? I see hessian PDFs being mentioned in this issue many times but standard NanoAODs don't have them. Would it be possible to have them in NanoAOD as well/instead? Personally I need the hessian ones for my analysis and I think a large number of analyses are dependent on them already.

**Comment by mariadalfonso** [comment]
PDF changed in cms-sw#31946

NNPDF NNPDF31_nnlo_hessian_pdfas is the preferred set for the V8 nano
Size increase  was modest ~ 2% https://github.com/cms-sw/cmssw/pull/31946#issuecomment-717822608
