### ISSUE TITLE
photons for FSR recovery?

### ISSUE THREAD

**Issue by singh-ramanpreet** [cms-nanoAOD/cmssw#178]
Hi,

I am trying to implement, FSR recovery, for H -> ZZ -> 4 lepton. I am not sure, if this can be done in nanoAOD since it requires PF photons with pT > 2 Gev.
(Section 3.3, [Analysis Note](http://cms.cern.ch/iCMS/jsp/openfile.jsp?tp=draft&files=AN2016_442_v8.pdf))

Thanks,
Raman

**Comment by gpetruc** [comment]
Indeed it can't be done with current nanoAOD. 

You could try add a list of candidate FSR photons, if it's small enough (ie empty in most events). However you can't easily subtract them from the leptons pf photon isolation since only the combined isolation is saved.

OTOH the 4l analysis may be better suited to miniAOD since you can redice the events early on in the processing flow skimming on the presence of many leptons, and profit from the richer event content (eg to retune object selections without having to wait for a new production)

**Comment by peruzzim** [comment]
closing this old issue
