### ISSUE TITLE
Generator weights as float16

### ISSUE THREAD

**Issue by intrepid42** [cms-nanoAOD/cmssw#189]
Hi, would it be an option to include generator weights as float16, similar to the packed formats in MiniAOD?

That would solve the space problem for incuding all PS weights needed for analysis (see https://github.com/cms-nanoAOD/cmssw/issues/110, https://github.com/cms-sw/cmssw/pull/24209)

It would not be human-readable anymore and require unpacking at analysis runtime though...

**Comment by intrepid42** [comment]
Hi, ok, good to know that the float size is already reduced!

Unfortunately, we are seeing many analyses right now that have overconstrained parton shower uncertainties in combine(-like) fits. The problematic user group in this case are not the MC experts (who would add it to their own nanoAOD) but the people who just use whatever is readily available*.

Seeing that many analyses are using combine nowadays I think it is important to make the decorrelated weights easily available for everyone.

Adding @smrenna @bendavid @perrozzi @efeyazgan @qliphy for info/discussion

*I am well aware that I belong to the second category for some other stuff

**Comment by arizzi** [comment]
I'm not sure I understood... so what? I mean what is the issue ?

**Comment by bendavid** [comment]
Hi,
I guess that so far only LHE weights (from LHEEventInfo) are being stored?

The parton shower weights are rather coming from GenEventInfo (because they are generated by pythia rather than the matrix element generator).

Incidentally in the SUSY parameter scan workflow, the matrix element weights also appear in GenEventInfo since the usual LHE products are bypassed.

**Comment by intrepid42** [comment]
@arizzi The problem is that the simple isr/fsr up/down weights lead to artificial nuisance constraints in combine fits. You define a standard here that 90% of the users will just follow, and I think it should be as robust as possible.

@bendavid Parton shower weights are included but they are hardcoded weights 6--9 in the GenEventInfoProduct

**Comment by arizzi** [comment]
@intrepid42,  ok then rather than isr/fsr up/down what else would you like to add ? how many weights? do we have a representation in eigenvectors of the covariance that can be used?

concerning the "artificial nuisance constraints" I'm afraid this is life.. if people put too many bins and too many events in the fit then nuisances are just constrained, if the constrain is artifical (as I'm sure it often is) a better[*] recipe than storing a zillion weights is probably to reduce the number of bins/events you fit

[*] better because anyhow or MC statistics is limited and the uncertainty on the difference between nominal and nuisanceUp/Down is not  properly taken into account during the fit

**Comment by intrepid42** [comment]
The extended set of weights can be found here: https://github.com/cms-sw/cmssw/blob/master/Configuration/Generator/python/PSweightsPythia/PythiaPSweightsSettings_cfi.py

People will always use the full available dataset, so we have to break down the uncertainties into uncorrelated sources wherever possible.

Taking MC stats correctly into account has to be done in the combine software, and I think other people are taking care of that part of the discussion.

**Comment by arizzi** [comment]
@intrepid42 well, I think as Giovanni said above, people can still run on their signal samples (= small stuff) a version of nano with many more PS weights.

Now the question and use case we have to cover with nanoaod is what is reasonable to do for the average user.
If the only argument for moving from 3 to 30 weights is "because otherwise people get artificial contraints in combine", I'm afraid this has little to do with 3 or 30 weights (of course 30 weights means less constraining).

**Comment by intrepid42** [comment]
I am mostly concerned about SM precision measurements. I don't know the exact impact on searches (where the backgrounds are also constrained in the fits) but the CDF Wjj story shows how things can go wrong with simplified systematics.

**Comment by gpetruc** [comment]
I don't think we can solve the problem of people not thinking at what they are doing just by adding more numbers to nanoAOD. And decorrelating any uncertainty into a large number of nuisances to avoid them being constrained does not necessarily give the correct answer 
Anyway, this is going beyond the topic of this issue, which per se can be closed since weights are already compressed.
I can open a new issue with the request of some feature and documentation for people to privately reproduce nanoAODs on some specific samples with an extended set of weights.
We could also extend the weights for some central samples that are not large and can be clearly identified as signal from LHE / GEN information, but not for the O(10B) full campaign.
