### ISSUE TITLE
JER Corrections

### ISSUE THREAD

**Issue by shane-breeze** [cms-nanoAOD/cmssw#202]
Is the recommended smearing procedure [1] for jet energy resolution applied to the `Jet` collection in nanoAOD or should this be applied on-the-fly to this collection?

[1] https://twiki.cern.ch/twiki/bin/view/CMS/JetResolution#Smearing_procedures

**Comment by ktht** [comment]
There's a nanoAOD-tools module for that ([link](https://github.com/cms-nanoAOD/nanoAOD-tools/blob/master/python/postprocessing/modules/jme/jetmetUncertainties.py)).

**Comment by peruzzim** [comment]
It's not applied in production, it would be very nice to have it.
The recommended procedure applies a random smearing for jets not matched to any generator-level jet, which is not ok for reproducibility.

For those cases, we should rather use a semi-deterministic approach as it is done for the EGM smearings (see EgammaAnalysis/ElectronTools/plugins/CalibratedElectronProducersRun2.cc).
In order to set the seed, we should use only variables for which precision is not lost in the nanoAOD production (so that one could later reproduce its behaviour in nanoAOD-tools module - avoid pt, phi etc.).

Would you please try implementing that in a producer?

**Comment by peruzzim** [comment]
@zdemirag @ahinzmann would you agree?

**Comment by zdemirag** [comment]
I also agree that to some level a deterministic approach is good way to go. In the this PR: https://github.com/cms-sw/cmssw/pull/20240 an option was added to the templates class to achieve the deterministic JER application. @eioannou: specifically this might be useful for the smeared MET and @rappoccio was part of this conversation in the past for the PR.

**Comment by mariadalfonso** [comment]
This topic is discussed in the context of the correction-lib to be added post-nano.
see here
https://github.com/cms-nanoAOD/correctionlib/issues/130
@zdemirag @ahinzmann you might want to contribute there 

I close this topic as nano-content will not be modified.
