### ISSUE TITLE
Electron_deltaEtaSC

### ISSUE THREAD

**Issue by yiiyama** [cms-nanoAOD/cmssw#216]
The electron deltaEtaSC variable currently defined here
https://github.com/cms-nanoAOD/cmssw/blob/master/PhysicsTools/NanoAOD/python/electrons_cff.py#L271
as `"superCluster().eta()-eta()"` is not quite what is used in the POG ID recommendation (https://github.com/ikrav/cmssw/blob/egm_id_80X_v1/RecoEgamma/ElectronIdentification/plugins/cuts/GsfEleDEtaInSeedCut.cc#L30-L33 linked from https://twiki.cern.ch/twiki/bin/view/CMS/CutBasedElectronIdentificationRun2). Is there a reason this specific definition was chosen, instead of this POG implementation or just straight `deltaEtaSuperClusterTrackAtVtx()`?
If there is a use case for the current definition, we would like to add a new variable that corresponds to the POG recommendation, because it was seen that the current NANOAOD deltaEtaSC has x10 worse resolution than the POG definition for truth-matched electrons. If there is not a known use case, we propose to simply change the definition. Please let me know what we can do here.

**Comment by gpetruc** [comment]
Hi,

That variable in the nanoAOD is meant to allow accessing the eta of the
supercluster, not for ID cuts.

Giovanni

Il Mar 30 Ott 2018, 22:03 Yutaro Iiyama <notifications@github.com> ha
scritto:

**Comment by peruzzim** [comment]
That variable is there to recover the SC eta, that can be used to bin scale factors or possibly for categorisation, without having to store that with the same precision of the electron eta (the difference between the two is close to zero, so it takes less bits to obtain the same precision).
Its meaning is completely different than the deltaEta used in electron ID.

The rationale here is that we don't support running complex object IDs that depend on several float variables on top of nanoAOD, because it would not be affordable in terms of event size.
The electron ID decision are available as bits that take much less space.

**Comment by yiiyama** [comment]
Hi @gpetruc @peruzzim , OK that makes sense. Thank you for the clarification.
