### ISSUE TITLE
LHE weights 

### ISSUE THREAD

**Issue by epalencia** [cms-nanoAOD/cmssw#330]
Dear experts,
this is a follow up of my talk in today's Top PAG meeting [1]. The issue is that, given that LHE weights are not always stored in the same order in miniAOD (as reported here [2]), we believe these weights are not properly stored in nAOD. Could you please check? 

   Enrique.

[1] https://indico.cern.ch/event/816475/contributions/3408242/attachments/1836494/3009192/topPAG_30apr2019.pdf

[2] https://hypernews.cern.ch/HyperNews/CMS/get/top-modeling-and-generators/299.html

**Comment by ktht** [comment]
Hi,

(disclaimer: I'm not a nanoAOD developer, but an early adopter)

As you mentioned, the LHE scale weights are not stored in the same order as in miniAOD because the order varies from MiniAOD to MiniAOD. For this reason, the access to LHE scale weights in NanoAOD is made universal by sorting the LHE scale weights in the following order:

```
mur=0.5 muf=0.5 
mur=0.5 muf=1 
mur=0.5 muf=2 
mur=1 muf=0.5 
mur=1 muf=1 
mur=1 muf=2 
mur=2 muf=0.5 
mur=2 muf=1 
mur=2 muf=2
```

This regex should cover all conventions:
https://github.com/cms-nanoAOD/cmssw/blob/9a2728ac9f44fc45ba1aa56389e28c594207c0fe/PhysicsTools/NanoAOD/plugins/GenWeightsTableProducer.cc#L305-L306

If you're unsure in what order the scale weights are stored, you can always get the ordering from branch title:

```cpp
TBranch * br = Events -> Get("LHEScaleWeight")
std::cout << br -> GetTitle() << '\n'
```

The same goes for PDF weights -- only one set of PDF weights is stored, which you can look up by printing out the title:
```cpp
TBranch * br = Events -> Get("LHEPdfWeight")
std::cout << br -> GetTitle() << '\n'
```

and compare against
https://github.com/cms-nanoAOD/cmssw/blob/9a2728ac9f44fc45ba1aa56389e28c594207c0fe/PhysicsTools/NanoAOD/python/nano_cff.py#L99-L104

The ordering above defines the priority of PDF sets: if, say, `PDF4LHC15_nnlo_30_pdfas` set is unavailable in MiniAOD, the next one (`NNPDF31_nnlo_hessian_pdfas`) is tried; if the second one in the list is also unavailable in MiniAOD, the next one in the list is tried etc until a PDF set is found, the corresponding weights of which are finally saved to NanoAOD.

So, the bottom line is that the scale weights are always saved in the same order and only one set of PDF weights are saved to NanoAOD (which you can determine by reading the title of `LHEPdfWeight` branch).

---

However, I want to piggyback this thread by raising another problem: it seems to me that in offically produced single-top NanoAOD Ntuples (THQ, THW), the LHE weights that restore the SM are missing. There are no rules to parse `rwgt_%d` and cmsDriver command [isn't configured](https://cms-pdmv.cern.ch/mcm/public/restapi/requests/get_setup/HIG-RunIIFall17NanoAOD-03300) for this special case, either.

**Comment by epalencia** [comment]
Thanks a lot for the explanations. Then, ME scale and PDF weights are ok (although different samples might have different PDF sets stored). But, what about PS weights? Something similar as for the ME scale weights is done?

**Comment by peruzzim** [comment]
@epalencia I'm afraid for PS weights we just take the order as given by `GenEventInfoProduct::weights()`
https://github.com/cms-nanoAOD/cmssw/blob/9a2728ac9f44fc45ba1aa56389e28c594207c0fe/PhysicsTools/NanoAOD/plugins/GenWeightsTableProducer.cc#L240-L246

To speed up checking and developing a fix, do you have an example of two files where you can prove that this issue happens?

**Comment by peruzzim** [comment]
> However, I want to piggyback this thread by raising another problem: it seems to me that in offically produced single-top NanoAOD Ntuples (THQ, THW), the LHE weights that restore the SM are missing. There are no rules to parse `rwgt_%d` and cmsDriver command [isn't configured](https://cms-pdmv.cern.ch/mcm/public/restapi/requests/get_setup/HIG-RunIIFall17NanoAOD-03300) for this special case, either.

@ktht I think you are correct, do you (or others) have a feeling on how many samples this is present? I remember at some point also this syntax changed (`mg_rwgt` maybe? or something similar).
As this is crucial information to use these samples, we could add this information.

**Comment by epalencia** [comment]
Below is the requested info: an example of an event with PSweights=1 in nAOD but sensibkle values in mAOD. Let me know if you need anything else.

===NanoAOD===
Dataset: /TTTo2L2Nu_TuneCP5_13TeV-powheg-pythia8/RunIIAutumn18NanoAODv4-Nano14Dec2018_102X_upgrade2018_realistic_v16-v1/NANOAODSIM
File: /store/mc/RunIIAutumn18NanoAODv4/TTTo2L2Nu_TuneCP5_13TeV-powheg-pythia8/NANOAODSIM/Nano14Dec2018_102X_upgrade2018_realistic_v16-v1/70000/1830E9AE-274F-B94D-848E-BA81CFA5F421.root
***********************************
Events->Scan("PSWeight","event==12290008")
***********************************
*    Row   * Instance *  PSWeight *
***********************************
*   945003 *        0 *         1 *
***********************************


===MiniAOD===
Dataset: /TTTo2L2Nu_TuneCP5_13TeV-powheg-pythia8/RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1/MINIAODSIM
File: /store/mc/RunIIAutumn18MiniAOD/TTTo2L2Nu_TuneCP5_13TeV-powheg-pythia8/MINIAODSIM/102X_upgrade2018_realistic_v15-v1/120000/B08EFFE4-4952-DD4D-A359-684E0D966FE4.root
Events->Scan("GenEventInfoProduct_generator__SIM.obj.weights_", "EventAuxiliary.id_.event_ == 12290009")
***********************************
*    Row   * Instance * GenEventI *
***********************************
*        0 *        0 *   72.6983 *
*        0 *        1 *   72.6983 *
*        0 *        2 *   72.6983 *
*        0 *        3 * 66.639474 *
*        0 *        4 *   72.6983 *
*        0 *        5 * 77.735098 *
*        0 *        6 *   72.6983 *
*        0 *        7 * 57.528712 *
*        0 *        8 *   72.6983 *
*        0 *        9 * 81.409632 *
*        0 *       10 *   72.6983 *
*        0 *       11 * 36.347061 *
*        0 *       12 *   72.6983 *
*        0 *       13 * 86.417854 *
*        0 *       14 * 61.351521 *
*        0 *       15 * 79.115014 *
*        0 *       16 * 67.473439 *
*        0 *       17 * 75.809574 *
*        0 *       18 *   72.6983 *
*        0 *       19 *   72.6983 *
*        0 *       20 * 73.447155 *
*        0 *       21 * 71.736690 *
*        0 *       22 *   72.6983 *
*        0 *       23 *   72.6983 *
*        0 *       24 *   72.6983 *
*        0 *       25 *   72.6983 *
*        0 *       26 *   72.6983 *
*        0 *       27 *   72.6983 *
*        0 *       28 *   72.6983 *
*        0 *       29 *   72.6983 *
*        0 *       30 *   72.6983 *
*        0 *       31 *   72.6983 *
*        0 *       32 *   72.6983 *
*        0 *       33 *   72.6983 *
*        0 *       34 *   72.6983 *
*        0 *       35 *   72.6983 *
*        0 *       36 *   72.6983 *
*        0 *       37 *   72.6983 *
*        0 *       38 *   72.6983 *
*        0 *       39 *   72.6983 *
*        0 *       40 *   72.6983 *
*        0 *       41 *   72.6983 *
*        0 *       42 *   72.6983 *
*        0 *       43 *   72.6983 *
*        0 *       44 *   72.6983 *
*        0 *       45 *   72.6983 *
***********************************

**Comment by peruzzim** [comment]
#331 #348

**Comment by peruzzim** [comment]
after investigations by @epalencia, added check for PS weight multiplicity == 46 in 2018 in #367 #369
