### ISSUE TITLE
Cut-based electron ID variables in nanoAOD

### ISSUE THREAD

**Issue by gpasztor** [cms-nanoAOD/cmssw#356]
While studying electron ID optimisation for a SUSY analyses, we discovered that some of the variables used in the cut-based electron ID are missing from nanoAOD:
- dEtaInSeed
- dPhiIn
- relIsoWithEA (maybe same as Electron_pfRelIso03_all?)
Could these be added to allow analysers to study performance on their own signals and to adjust cuts if/when needed?
Thanks, Gabi

**Comment by peruzzim** [comment]
The central NanoAOD is not meant to develop or optimize object ID on top of it.
The design choice was to support ID decisions, analyzers can easily run a private version on a small set of datasets for this kind of studies, adding the variables that are needed.
Otherwise it would be impossible to keep the data format compact enough.
