### ISSUE TITLE
HLT Muons in TrigObj collection

### ISSUE THREAD

**Issue by shane-breeze** [cms-nanoAOD/cmssw#397]
I've looked for HLT muons with the DYJetsToLL nanoAOD samples in the TrigObj collection by requiring an id of 13, but no such entries exist. However, a dR match between offline reconstructed muons and a TrigObj exists with id==1, supposedly a jet. Does some preference need to be placed on assigning the TrigObj to a muon rather than a jet? Currently the TrigObj filter bits for the HLT muons are lost since it's considered a HLT jet. Also, dR matching offline muons to HLT jets may result in mismatching

**Comment by peruzzim** [comment]
I am not aware of any preference of such kind. The only thing that looks like a cleaning only happens between HLT objects with the same id, so it should have no effect.

Could I ask you to check in the corresponding MINIAOD sample, whether the HLT muons are there and pass the selection defined here?

https://github.com/cms-nanoAOD/cmssw/blob/4147ed99eef33d0145db3ae96fa2a87387fe1e75/PhysicsTools/NanoAOD/python/triggerObjects_cff.py#L61

It is challenging to maintain the configuration in this file, because of the variability of HLT paths and modules. The code creating the table of HLT objects is in PhysicsTools/NanoAOD/plugins/TriggerObjectTableProducer.cc, please take a look at it. It should be pretty user-friendly for you to go through and check whether you can spot any issue with it.

**Comment by peruzzim** [comment]
has this been further investigated?

**Comment by shane-breeze** [comment]
Sorry, I was busy and managed to miss your original reply. I haven't looked into this any further. I will try to look into it when I have some time, but this isn't high on my priority list right now

**Comment by vlimant** [comment]
please ping / reopen in cams-sw if still required.
