### ISSUE TITLE
investigate JEC uncertainties via weights

### ISSUE THREAD

**Issue by gpetruc** [cms-nanoAOD/cmssw#42]
try computing weights as function of ptreco/ptgen instead of shifting ptreco

**Comment by arizzi** [comment]
ttHbb people tested it (to avoid redoing MEM with Jec variations) and Lorenzo says that we need to be careful about correlations when we compute the ptreco/ptgen that are lost in a simple pt,eta binning.
It was observed that e.g. dijet invariant mass was not well reproduced and the hint from lorenzo is that it could be due to different response when there are two closeby jets.

bottom line: we should see if a binning vs "closest jet deltaR" would lead to different distributions in different bins

In addition the distributions must be computed with properly reweighted PU

**Comment by vlimant** [comment]
ping / reopen if needed
