### ISSUE TITLE
extend the electron matching

### ISSUE THREAD

**Issue by mariadalfonso** [cms-nanoAOD/cmssw#552]
See report from Sergio
https://indico.cern.ch/event/962278/contributions/4060711/attachments/2136665/3599026/electron_matching_nano_nov4.pdf

to do: extend the GenDressedLeptons at lower pt

**Comment by sscruz** [comment]
hi @mariadalfonso , all, 
I have implemented the matching to GenDressedLeptons in the matching. The approach recovers a similar level to efficiency to the other approaches I showed during the meeting. In particular, I have checked that the procedure agrees with the matching to status=1 OR isLastCopyBeforeFSR to a level below 0.1%. 

However, this is a bit more tricky than what I initially thought and I had to make several decisions to implement this. Let me know if this is fine: 

- As suggested by @peruzzim, I have lowered the GenDressedLepton and GenIsolatedPhoton thresholds for the matching, but I haven't modified the collection that is stored.
- I have kept the Electron_genPartIdx variable as it is, as it points to GenParticles, not to GenDressedLeptons (part of which are not stored)
- Matching electrons to GenDressedLeptons / GenIsolatedPhotons only does not allow to identify the origin of nonprompt leptons. In order to fix that, I've implemented a logic in which: 1) I try to match electrons to GenDressedLeptons / GenIsolatedPhotons and then, if (1) fails it tries to match them to status==1 particles, using the current logic. I guess this is a bit messy, I'm happy to hear other options. 

Also, I have validated that this approach does not affect significantly the fake rate. I'm plotting below the number of electrons matched to prompt electrons or taus in a DY->LL sample, showing that the number of matched electrons above 2 does not increase very significantly. 

[plot_withlog.pdf](https://github.com/cms-nanoAOD/cmssw/files/5510799/plot_withlog.pdf)
[plot_nolog.pdf](https://github.com/cms-nanoAOD/cmssw/files/5510800/plot_nolog.pdf)


You can find the implementation of this in sscruz:from-CMSSW_10_2_22_electronMatching, it is based (as nanoAOD v7) in CMSSW_10_2_22. I could rebase it to the master branch. Could you let me know on which cmssw release is cms-nanoAOD:master based?

**Comment by bendavid** [comment]
How is the genPartIdx filled in cases where a GenDressedLepton is matched?  (It should be possible to determine the constituent electron from the GenDressedLepton somehow)

**Comment by sscruz** [comment]
Right now, I'm keeping the same index as it is right now. Ie, in cases in which the electron is matched to a GenDressedLepton but not to  a status==1 GenParticle, genPartIdx is equal to-1... I guess it should be possible to match that to a GenParticle. Do you know of an existing implementation of that? I really wouldn't like to reinvent the wheel there :)

**Comment by mariadalfonso** [comment]
@sscruz  @bendavid @peruzzim 
was there any decision on how to extend the electron matching ?

**Comment by bendavid** [comment]
The genparticle(s) should be easily accessible from the relevant accessors.  I'm not aware of any ready-made solution.

https://github.com/cms-sw/cmssw/blob/ba6e8604a35283e39e89bc031766843d0afc3240/DataFormats/JetReco/interface/GenJet.h#L109-L114

It's PROBABLY the first constituent, but can explicitly select e.g. the highest pt constituent with abs(pdgid) 11

**Comment by sscruz** [comment]
hi @mariadalfonso , @bendavid , thanks a lot for the pointer. I have implemented that logic (picking the highest pt constituent with abs(pdgid) == 11) in sscruz:from-CMSSW_10_2_22_electronMatching. The only caveat is that I don't know of a way to link the constituents to the finalGenParticles, so i did a deltaR && deltaPt matching, which is quite dirty but works. If you have suggestions here I'm happy to implement it. If not,  I can rebase and make a PR. 
Cheers

**Comment by bendavid** [comment]
Hi, you mean the highest pt constitution with abs(pdgid) == 11 I guess rather than pt>11 ? :)

**Comment by sscruz** [comment]
hi, yes, of course, sorry, too much coding today :) i've edited it

**Comment by bendavid** [comment]
You can get the index of the genParticle in the collection used to build the dressed leptons with getJetConstituents()[i].key(), but I'm not sure how easy it is to then match this up with the index in the finalGenParticles

**Comment by sscruz** [comment]
yeah, the problem is that I couldn't find a way to do the latter. I'm also not sure a reference from the finalGenParticles to the initial collection that is used to build the constituents is kept. Anyway, the matching with dR,dPt/pt seems to be good enough. 
@mariadalfonso  should i go ahead and make a PR?

**Comment by mariadalfonso** [comment]
> @mariadalfonso should i go ahead and make a PR?

yes, go ahead with a PR in master, so that we can review the coding details

**Comment by mariadalfonso** [comment]
closing this since has been handled
