### ISSUE TITLE
Nan with quark-gluon in NanoAOD

### ISSUE THREAD

**Issue by mariadalfonso** [cms-nanoAOD/cmssw#556]
reported here 
https://indico.cern.ch/event/962278/#7-issues-with-quark-gluon-in-n

**Comment by mariadalfonso** [comment]
From @alefisico
I think this is related with a mismatch of QGL databases in the global tags reported to us last week. To summarize: 
2018UL MC GT: QGLikelihoodObject_v1_AK4PFchs (2015 training)
2017UL MC GT: QGLikelihoodObject_v1_AK4PFchs_2017 (2017 training)
2016UL MC GT(preVFP, postVFP): QGLikelihoodObject_v1_AK4PFchs_2016 (2016 training)
Data GT: QGLikelihoodObject_v1_AK4PFchs (2015 training) — the same GT is used for all three years,

It should be the 2017 training everywhere (until we have dedicated UL trainings).

As extra information, we know that the 2015 trainings can produced these Nan-values.

**Comment by hqucms** [comment]
FYI -- We have requested new GTs from AlCa/DB to fix this:
https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/4357.html

**Comment by mariadalfonso** [comment]
added in the GT with PR
#32247

**Comment by mariadalfonso** [comment]
I still see a lot of nan for nanoV8 campaign

here is some way to reproduce them 

root://xrootd-cms.infn.it//store/mc/RunIISummer20UL18NanoAODv2/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8/NANOAODSIM/106X_upgrade2018_realistic_v15_L1v1-v1/20000/A2B51438-22E7-C440-9490-B75A84BBBB3F.root

FOUND nan in Jet_qgl[0] run:lumi:event 1:132039:132038327
FOUND nan in Jet_qgl0] run:lumi:event 1:341110:341109793
FOUND nan in Jet_qgl[0]  run:lumi:event 1:130399:130398301
...

**Comment by alefisico** [comment]
Hi, 
sorry for the late reply. 
We dont rerun QGL in nanoAOD, we take the value directly from miniAOD. The nanoAODv8 file that you posted is done with the [global tag](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/106X_upgrade2018_realistic_v15_L1v1) where the correct QGL training is included but the miniAOD parent is done with an older global tag (`106X_upgrade2018_realistic_v11_L1v1`). 
This problem is solved if the re-miniAOD campaing was done with the `106X_upgrade2018_realistic_v15_L1v1` global tag.

**Comment by alefisico** [comment]
Hi @mariadalfonso 
after further checks and discussions about this issue, it looks like what I said before is not true. We are looking into ways of fixing this issue asap. Maybe you should open this issue again.

**Comment by mariadalfonso** [comment]
a protection being added in

https://github.com/cms-sw/cmssw/pull/33925/files#diff-377770d6a7d4705da48aa96709bdedefcb42d5b5497c85ba41a3f11074c148a0R243
