### ISSUE TITLE
MuonMVAid in nano

### ISSUE THREAD

**Issue by mariadalfonso** [cms-nanoAOD/cmssw#588]
This is now added in cms-sw
https://github.com/cms-sw/cmssw/pull/36179

we should in a separate PR also add in nano

**Comment by mariadalfonso** [comment]
@sscruz @andrea21z 
please take note

**Comment by sscruz** [comment]
hi @mariadalfonso
thanks for starting the thread! I'm wondering how we should proceed for this. The situation is right now is that pat::Muons in miniAODv2 won't contain this selector, but miniAODs produced on Run 3 will contain it. 

Therefore it is straightforward to include the selector in Run 3 nanoAOD, but we would need to recompute it on top of miniAOD for Run 2 dataset. Is there some nanoAODv3 foreseen for Run 2 in the future, so that it is updated with respect to Run3? 
Thanks!

(adding @gkaratha and @cramonal)

**Comment by mariadalfonso** [comment]
@sscruz

yes there will be a renano V10 with the same analysis feature/algorithm developed for run3.

**Comment by sscruz** [comment]
thanks! and no miniv3? in such case, we will have to integrate a module that computes the mva during nanoaod production for run2 data/mc

**Comment by mariadalfonso** [comment]
@sscruz

any news on this ?

**Comment by swertz** [comment]
Handled in https://github.com/cms-sw/cmssw/pull/39355

**Comment by vlimant** [comment]
we will keep track of things for V11 in the googledoc : https://docs.google.com/document/d/1UaAEmLBbA8upMzIZ4Rnv5__ychOsEVBDecca0zHAQ4I/edit?usp=sharing or directly in the cm-sw GH
