### ISSUE TITLE
photon trigger infos inadeguate for trig eff measuremen

### ISSUE THREAD

**Issue by mariadalfonso** [cms-nanoAOD/cmssw#592]
https://hypernews.cern.ch/HyperNews/CMS/get/physTools/3823.html

discussed more on mattermost https://mattermost.web.cern.ch/cmseg/pl/tk1or3scotynbn1yf3so4mmtya

**Comment by bartokm** [comment]
Main issue is, that starting from nanoAODv7 the photon trigger objects were never saved. But even before that the photon trigger object was ill-defined.

Details:
https://github.com/cms-sw/cmssw/blob/master/PhysicsTools/NanoAOD/python/triggerObjects_cff.py#L51-L59
Photon trigger objects don't have any filters. Since a "skim" was added in v7 (skipObjectsNotPassingQualityBits) only trigger objects with passed filters were saved, hence: no photon trigger objects were saved.
But in general, the photon trigger object definition is incorrect. As I was told by egamma experts, the pixelseed veto (!filter('*PixelMatchFilter')) should be removed, since in HLT for most photon paths pixel veto is not required.

Fixing the issue:
1) Remove !filter('*PixelMatchFilter') in definition
2) Add filters for photon trigger objects

**Comment by mariadalfonso** [comment]
done in cms-sw 39043
